heat_template_version: '2016-10-14'

description: >
  Single BSD instance attached to the network 'network'
  Version: 23MAR18

parameters:
  name:
    type: string
    default: bsd_inst
  flavor:
    type: string
    default: cy.large
  image:
    type: string
    default: "FreeBSD_11.1_1"
  username:
    type: string
    default: user
  password:
    type: string
    hidden: true
    default: pass
  network:
    type: string
    default: network

resources:

  host:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: 
        - network: { get_param: network }

